apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/default-container: captured
    kubectl.kubernetes.io/default-logs-container: captured
    linkerd.io/inject: disabled
    prometheus.io/path: /stats/prometheus
    prometheus.io/port: "15020"
    prometheus.io/scrape: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/interceptionMode: REDIRECT
    sidecar.istio.io/proxyCPU: 1000m
    sidecar.istio.io/proxyMemory: 512Mi
    sidecar.istio.io/status: '{"initContainers":["istio-init","enable-core-dump"],"containers":["istio-proxy"],"volumes":["workload-socket","credential-socket","workload-certs","istio-envoy","istio-data","istio-podinfo","istio-token","istiod-ca-cert"],"imagePullSecrets":null,"revision":"default"}'
    traffic.sidecar.istio.io/excludeInboundPorts: 8076,8077,8078,8081,9999
    traffic.sidecar.istio.io/excludeOutboundPorts: 80,8076,8077,8078, 8081
  creationTimestamp: "2023-02-28T18:47:19Z"
  generateName: fortioserver-7bc49d657f-
  labels:
    app: fortioserver
    pod-template-hash: 7bc49d657f
    security.istio.io/tlsMode: istio
    service.istio.io/canonical-name: fortioserver
    service.istio.io/canonical-revision: latest
  name: fortioserver-7bc49d657f-smvpb
  namespace: twopods-istio
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: fortioserver-7bc49d657f
    uid: c2388b79-5dfa-48af-88e3-bdc2d5bb5386
  resourceVersion: "8248253"
  uid: 71b6af7b-4f10-4cf5-8b0c-2b6041644dc7
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - fortioclient
        topologyKey: kubernetes.io/hostname
  containers:
  - image: fortio/fortio:latest_release
    imagePullPolicy: IfNotPresent
    name: captured
    ports:
    - containerPort: 8080
      protocol: TCP
    - containerPort: 8079
      protocol: TCP
    - containerPort: 8078
      protocol: TCP
    resources:
      requests:
        cpu: 1500m
        memory: 1000Mi
    securityContext:
      runAsUser: 1
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/fortio
      name: shared-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-64pwl
      readOnly: true
  - args:
    - /bin/sleep
    - 3650d
    image: cfmanteiga/alpine-bash-curl-jq:latest
    imagePullPolicy: Always
    name: shell
    resources: {}
    securityContext:
      runAsUser: 1
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/fortio
      name: shared-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-64pwl
      readOnly: true
  - args:
    - server
    - -http-port
    - "8077"
    - -grpc-port
    - "8076"
    - -tcp-port
    - "8078"
    - -redirect-port
    - "8081"
    image: fortio/fortio:latest_release
    imagePullPolicy: IfNotPresent
    name: uncaptured
    resources:
      requests:
        cpu: 1500m
        memory: 1000Mi
    securityContext:
      runAsUser: 1
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-64pwl
      readOnly: true
  - args:
    - proxy
    - sidecar
    - --domain
    - $(POD_NAMESPACE).svc.cluster.local
    - --proxyLogLevel=warning
    - --proxyComponentLogLevel=misc:error
    - --log_output_level=default:info
    - --concurrency
    - "2"
    env:
    - name: JWT_POLICY
      value: third-party-jwt
    - name: PILOT_CERT_PROVIDER
      value: istiod
    - name: CA_ADDR
      value: istiod.istio-system.svc:15012
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: INSTANCE_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.serviceAccountName
    - name: HOST_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: PROXY_CONFIG
      value: |
        {"proxyMetadata":{"ISTIO_META_DNS_CAPTURE":"true"}}
    - name: ISTIO_META_POD_PORTS
      value: |-
        [
            {"containerPort":8080,"protocol":"TCP"}
            ,{"containerPort":8079,"protocol":"TCP"}
            ,{"containerPort":8078,"protocol":"TCP"}
        ]
    - name: ISTIO_META_APP_CONTAINERS
      value: captured,shell,uncaptured
    - name: ISTIO_META_CLUSTER_ID
      value: Kubernetes
    - name: ISTIO_META_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: ISTIO_META_INTERCEPTION_MODE
      value: REDIRECT
    - name: ISTIO_META_WORKLOAD_NAME
      value: fortioserver
    - name: ISTIO_META_OWNER
      value: kubernetes://apis/apps/v1/namespaces/twopods-istio/deployments/fortioserver
    - name: ISTIO_META_MESH_ID
      value: cluster.local
    - name: TRUST_DOMAIN
      value: cluster.local
    - name: ISTIO_META_DNS_CAPTURE
      value: "true"
    image: gcr.io/istio-testing/proxyv2:1.18-alpha.31385251050c9efdddc2c14116f5b8eb845200b5
    imagePullPolicy: IfNotPresent
    name: istio-proxy
    ports:
    - containerPort: 15090
      name: http-envoy-prom
      protocol: TCP
    readinessProbe:
      failureThreshold: 30
      httpGet:
        path: /healthz/ready
        port: 15021
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 2
      successThreshold: 1
      timeoutSeconds: 3
    resources:
      requests:
        cpu: "1"
        memory: 512Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: false
      runAsGroup: 1337
      runAsNonRoot: true
      runAsUser: 1337
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/workload-spiffe-uds
      name: workload-socket
    - mountPath: /var/run/secrets/credential-uds
      name: credential-socket
    - mountPath: /var/run/secrets/workload-spiffe-credentials
      name: workload-certs
    - mountPath: /var/run/secrets/istio
      name: istiod-ca-cert
    - mountPath: /var/lib/istio/data
      name: istio-data
    - mountPath: /etc/istio/proxy
      name: istio-envoy
    - mountPath: /var/run/secrets/tokens
      name: istio-token
    - mountPath: /etc/istio/pod
      name: istio-podinfo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-64pwl
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - args:
    - istio-iptables
    - -p
    - "15001"
    - -z
    - "15006"
    - -u
    - "1337"
    - -m
    - REDIRECT
    - -i
    - '*'
    - -x
    - ""
    - -b
    - '*'
    - -d
    - 15090,15021,8076,8077,8078,8081,9999,15020
    - -o
    - 80,8076,8077,8078, 8081
    - --log_output_level=default:info
    env:
    - name: ISTIO_META_DNS_CAPTURE
      value: "true"
    image: gcr.io/istio-testing/proxyv2:1.18-alpha.31385251050c9efdddc2c14116f5b8eb845200b5
    imagePullPolicy: IfNotPresent
    name: istio-init
    resources:
      requests:
        cpu: "1"
        memory: 512Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: false
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-64pwl
      readOnly: true
  - args:
    - -c
    - sysctl -w kernel.core_pattern=/var/lib/istio/data/core.proxy && ulimit -c unlimited
    command:
    - /bin/sh
    image: gcr.io/istio-testing/proxyv2:1.18-alpha.31385251050c9efdddc2c14116f5b8eb845200b5
    imagePullPolicy: IfNotPresent
    name: enable-core-dump
    resources:
      requests:
        cpu: "1"
        memory: 512Mi
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - SYS_ADMIN
        drop:
        - ALL
      privileged: true
      readOnlyRootFilesystem: false
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-64pwl
      readOnly: true
  nodeName: aks-nodepool2-17732352-vmss00002g
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - emptyDir: {}
    name: workload-socket
  - emptyDir: {}
    name: credential-socket
  - emptyDir: {}
    name: workload-certs
  - emptyDir:
      medium: Memory
    name: istio-envoy
  - emptyDir: {}
    name: istio-data
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels
        path: labels
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations
        path: annotations
    name: istio-podinfo
  - name: istio-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: istio-ca
          expirationSeconds: 43200
          path: istio-token
  - configMap:
      defaultMode: 420
      name: istio-ca-root-cert
    name: istiod-ca-cert
  - emptyDir: {}
    name: shared-data
  - name: kube-api-access-64pwl
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-02-28T18:47:25Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-03-07T03:38:55Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-03-07T03:38:55Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-02-28T18:47:19Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://418a32f7a3b919db6157301041b66aa3e7cf17ce93376c8ccf33fb12561aa691
    image: docker.io/fortio/fortio:latest_release
    imageID: docker.io/fortio/fortio@sha256:0b49b212f19bc1dc8f39e5f522dc3d36be9491c52c721d3cc9b5932ed42896a8
    lastState: {}
    name: captured
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-02-28T18:47:26Z"
  - containerID: containerd://10ccabe0f2b9cc8f516720d19409f53d0f32a123c3629316cf1a1c943d559d15
    image: gcr.io/istio-testing/proxyv2:1.18-alpha.31385251050c9efdddc2c14116f5b8eb845200b5
    imageID: gcr.io/istio-testing/proxyv2@sha256:730cd53cb5057afe6893afdda7bfa29fdfe16d15cad20a4373b9593caf05e8e7
    lastState:
      terminated:
        containerID: containerd://f8931e703202ce6b490e641f828ca4dd2dab39acdcaa950153d4396d88ad0657
        exitCode: 0
        finishedAt: "2023-03-07T03:38:53Z"
        reason: Completed
        startedAt: "2023-03-07T02:46:17Z"
    name: istio-proxy
    ready: true
    restartCount: 13
    started: true
    state:
      running:
        startedAt: "2023-03-07T03:38:54Z"
  - containerID: containerd://7e7d9a04dadc89b46b6d4d2db2afebadf0469afd48201e076e6c852ae7969b0a
    image: docker.io/cfmanteiga/alpine-bash-curl-jq:latest
    imageID: docker.io/cfmanteiga/alpine-bash-curl-jq@sha256:e09a3d5d52abb27830b44a2c279d09be66fad5bf476b3d02fb4a4a6125e377fc
    lastState: {}
    name: shell
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-02-28T18:47:26Z"
  - containerID: containerd://ee6511435d8885cce7f08224665421894c9207d6f294034c1697c9d714abc7b5
    image: docker.io/fortio/fortio:latest_release
    imageID: docker.io/fortio/fortio@sha256:0b49b212f19bc1dc8f39e5f522dc3d36be9491c52c721d3cc9b5932ed42896a8
    lastState: {}
    name: uncaptured
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-02-28T18:47:26Z"
  hostIP: 10.224.0.17
  initContainerStatuses:
  - containerID: containerd://0712b048f7ac85fa1c654111acb6a627d8baf44ad3f2e6ac4fea7c2a80e56aec
    image: gcr.io/istio-testing/proxyv2:1.18-alpha.31385251050c9efdddc2c14116f5b8eb845200b5
    imageID: gcr.io/istio-testing/proxyv2@sha256:730cd53cb5057afe6893afdda7bfa29fdfe16d15cad20a4373b9593caf05e8e7
    lastState: {}
    name: istio-init
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: containerd://0712b048f7ac85fa1c654111acb6a627d8baf44ad3f2e6ac4fea7c2a80e56aec
        exitCode: 0
        finishedAt: "2023-02-28T18:47:23Z"
        reason: Completed
        startedAt: "2023-02-28T18:47:23Z"
  - containerID: containerd://b7dde0322d89f50d5a9cb7c06b0bf52b7b7bc40f2037055c131e6dc3985bd50d
    image: gcr.io/istio-testing/proxyv2:1.18-alpha.31385251050c9efdddc2c14116f5b8eb845200b5
    imageID: gcr.io/istio-testing/proxyv2@sha256:730cd53cb5057afe6893afdda7bfa29fdfe16d15cad20a4373b9593caf05e8e7
    lastState: {}
    name: enable-core-dump
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: containerd://b7dde0322d89f50d5a9cb7c06b0bf52b7b7bc40f2037055c131e6dc3985bd50d
        exitCode: 0
        finishedAt: "2023-02-28T18:47:24Z"
        reason: Completed
        startedAt: "2023-02-28T18:47:24Z"
  phase: Running
  podIP: 10.244.13.2
  podIPs:
  - ip: 10.244.13.2
  qosClass: Burstable
  startTime: "2023-02-28T18:47:19Z"
