# Source: pilot/templates/services.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: fortio-gateway
spec:
  servers:
  - hosts:
    - fortioclient.local
    port:
      name: http
      number: 80
      protocol: HTTP
---
# Source: pilot/templates/services.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fortioclient
spec:
  hosts:
  - fortioclient.local
  gateways:
  - fortio-gateway
  http:
  - route:
    - destination:
        host: fortioclient
        port:
          number: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
      annotations:
        sidecar.istio.io/inject: "false"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - args:
        - load
        - -c
        - "{{ .Values.connections }}"
        - -qps
        - "{{ .Values.qps }}"
        - -t
        - "{{ .Values.runDuration }}"
        - -r
        - "0.0001"
{{- range $a, $s := .Values.additionalHeaders }}
        - -H
        - "{{$a}}: {{$s}}"
{{- end }}
        - -H
        - "Host: {{ .Values.serviceHost }}"
{{- if .Values.https }}
        - -resolve
        - {{ .Values.ingress }}
        - -k
        - "https://{{ .Values.serviceHost }}/{{ .Values.serviceURL  }}"
{{- else }}
        - "http://{{ .Values.ingress }}/{{ .Values.serviceURL  }}"
{{- end }}
        image: {{ .Values.image }}
        name: fortio
        ports:
        - containerPort: 8080
        # - containerPort: 42422
---
apiVersion: v1
kind: Service
metadata:
  name: fortioclient
spec:
  ports:
  - name: http-echo
    port: 8080
    protocol: TCP
  selector:
    app: fortioclient
  type: LoadBalancer