# Data: cpu/mem
# Config: No telemetry
telemetry_mode: "none"
conn:
    - 16
qps:
    - 10
    - 100
    - 200
    - 400
    - 800
    - 1000
    - 1200
    - 1400
    - 1600
    - 1800
    - 2000
duration: 240
perf_record: false
run_bothsidecar: true
run_serversidecar: false
run_clientsidecar: false
run_baseline: true

extra_labels: "no_jitter"

jitter: false
