# Data: latency
# Config: No telemetry
telemetry_mode: "none"
# conn:
#     - 2
#     - 4
#     - 8
#     - 16
#     - 32
#     - 64
# qps:
#     - 1000
conn:
    - 16
qps:
    - 10
    - 100
    - 200
    - 400
    - 800
    - 1000
duration: 240
size: 1024
perf_record: false
run_bothsidecar: true
run_serversidecar: false
run_clientsidecar: false
run_baseline: true

extra_labels: "jitter"
jitter: true
