# Data: latency
# Config: No telemetry
telemetry_mode: "none"
conn:
    - 2
    - 4
    - 8
    - 16
    - 32
    - 64
qps:
    - 1000
duration: 300
size: 1024
perf_record: false
run_bothsidecar: true
run_serversidecar: false
run_clientsidecar: false
run_baseline: true

extra_labels: ""
nocatchup: true
uniform: true
jitter: false
