{{ range until (int .Values.serviceEntries) }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: ext-svc-{{.}}
spec:
  hosts:
    - www.google.com
  ports:
    - number: 80
      name: http
      protocol: HTTP
  resolution: DNS
---
{{ end }}