apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/default-container: captured
    kubectl.kubernetes.io/default-logs-container: captured
    linkerd.io/inject: disabled
    prometheus.io/path: /stats/prometheus
    prometheus.io/port: "15020"
    prometheus.io/scrape: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/interceptionMode: REDIRECT
    sidecar.istio.io/proxyCPU: 1000m
    sidecar.istio.io/proxyMemory: 512Mi
    sidecar.istio.io/status: '{"initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["workload-socket","credential-socket","workload-certs","istio-envoy","istio-data","istio-podinfo","istio-token","istiod-ca-cert"],"imagePullSecrets":null,"revision":"asm-1-17"}'
    traffic.sidecar.istio.io/excludeInboundPorts: 8076,8077,8078,8081,9999
    traffic.sidecar.istio.io/excludeOutboundPorts: 80,8076,8077,8078, 8081
    traffic.sidecar.istio.io/includeOutboundIPRanges: 10.0.0.0/16
  creationTimestamp: "2023-10-25T00:13:26Z"
  generateName: fortioclient-7fd7b6b8cf-
  labels:
    app: fortioclient
    pod-template-hash: 7fd7b6b8cf
    security.istio.io/tlsMode: istio
    service.istio.io/canonical-name: fortioclient
    service.istio.io/canonical-revision: latest
  name: fortioclient-7fd7b6b8cf-bbclp
  namespace: test
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: fortioclient-7fd7b6b8cf
    uid: 92a39135-3944-4d0c-a59f-3633588bea48
  resourceVersion: "38070053"
  uid: 149a914e-f768-4066-8040-8c2cfed8b03d
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - fortioserver
        topologyKey: kubernetes.io/hostname
  containers:
  - args:
    - report
    image: fortio/fortio:latest_release
    imagePullPolicy: IfNotPresent
    name: captured
    resources:
      requests:
        cpu: 1500m
        memory: 1000Mi
    securityContext:
      runAsUser: 1
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/fortio
      name: shared-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-dd7k6
      readOnly: true
  - args:
    - /bin/sleep
    - 3650d
    image: cfmanteiga/alpine-bash-curl-jq:latest
    imagePullPolicy: Always
    name: shell
    resources: {}
    securityContext:
      runAsUser: 1
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/fortio
      name: shared-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-dd7k6
      readOnly: true
  - args:
    - report
    - -http-port
    - "8077"
    - -grpc-port
    - "8076"
    - -redirect-port
    - "8081"
    - -tcp-port
    - "8078"
    image: fortio/fortio:latest_release
    imagePullPolicy: IfNotPresent
    name: uncaptured
    resources:
      requests:
        cpu: 1500m
        memory: 1000Mi
    securityContext:
      runAsUser: 1
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-dd7k6
      readOnly: true
  - args:
    - proxy
    - sidecar
    - --domain
    - $(POD_NAMESPACE).svc.cluster.local
    - --proxyLogLevel=warning
    - --proxyComponentLogLevel=misc:error
    - --log_output_level=default:info
    - --concurrency
    - "2"
    env:
    - name: JWT_POLICY
      value: third-party-jwt
    - name: PILOT_CERT_PROVIDER
      value: istiod
    - name: CA_ADDR
      value: istiod-asm-1-17.aks-istio-system.svc:15012
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: INSTANCE_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.serviceAccountName
    - name: HOST_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: PROXY_CONFIG
      value: |
        {"discoveryAddress":"istiod-asm-1-17.aks-istio-system.svc:15012","tracing":{"zipkin":{"address":"zipkin.aks-istio-system:9411"}},"gatewayTopology":{"numTrustedProxies":1},"image":{"imageType":"distroless"}}
    - name: ISTIO_META_POD_PORTS
      value: |-
        [
        ]
    - name: ISTIO_META_APP_CONTAINERS
      value: captured,shell,uncaptured
    - name: ISTIO_META_CLUSTER_ID
      value: Kubernetes
    - name: ISTIO_META_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: ISTIO_META_INTERCEPTION_MODE
      value: REDIRECT
    - name: ISTIO_META_WORKLOAD_NAME
      value: fortioclient
    - name: ISTIO_META_OWNER
      value: kubernetes://apis/apps/v1/namespaces/test/deployments/fortioclient
    - name: ISTIO_META_MESH_ID
      value: cluster.local
    - name: TRUST_DOMAIN
      value: cluster.local
    image: mcr.microsoft.com/oss/istio/proxyv2:1.17.8-distroless
    imagePullPolicy: IfNotPresent
    name: istio-proxy
    ports:
    - containerPort: 15090
      name: http-envoy-prom
      protocol: TCP
    readinessProbe:
      failureThreshold: 30
      httpGet:
        path: /healthz/ready
        port: 15021
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 2
      successThreshold: 1
      timeoutSeconds: 3
    resources:
      requests:
        cpu: "1"
        memory: 512Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 1337
      runAsNonRoot: true
      runAsUser: 1337
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/workload-spiffe-uds
      name: workload-socket
    - mountPath: /var/run/secrets/credential-uds
      name: credential-socket
    - mountPath: /var/run/secrets/workload-spiffe-credentials
      name: workload-certs
    - mountPath: /var/run/secrets/istio
      name: istiod-ca-cert
    - mountPath: /var/lib/istio/data
      name: istio-data
    - mountPath: /etc/istio/proxy
      name: istio-envoy
    - mountPath: /var/run/secrets/tokens
      name: istio-token
    - mountPath: /etc/istio/pod
      name: istio-podinfo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-dd7k6
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - args:
    - istio-iptables
    - -p
    - "15001"
    - -z
    - "15006"
    - -u
    - "1337"
    - -m
    - REDIRECT
    - -i
    - 10.0.0.0/16
    - -x
    - ""
    - -b
    - '*'
    - -d
    - 15090,15021,8076,8077,8078,8081,9999,15020
    - -o
    - 80,8076,8077,8078, 8081
    - --log_output_level=default:info
    image: mcr.microsoft.com/oss/istio/proxyv2:1.17.8-distroless
    imagePullPolicy: IfNotPresent
    name: istio-init
    resources:
      requests:
        cpu: "1"
        memory: 512Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: false
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-dd7k6
      readOnly: true
  nodeName: aks-userpool-37238964-vmss00001m
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - emptyDir: {}
    name: workload-socket
  - emptyDir: {}
    name: credential-socket
  - emptyDir: {}
    name: workload-certs
  - emptyDir:
      medium: Memory
    name: istio-envoy
  - emptyDir: {}
    name: istio-data
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels
        path: labels
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations
        path: annotations
    name: istio-podinfo
  - name: istio-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: istio-ca
          expirationSeconds: 43200
          path: istio-token
  - configMap:
      defaultMode: 420
      name: istio-ca-root-cert
    name: istiod-ca-cert
  - emptyDir: {}
    name: shared-data
  - name: kube-api-access-dd7k6
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-10-25T00:13:28Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-10-25T00:13:37Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-10-25T00:13:37Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-10-25T00:13:26Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://5091a7af05fac61f84d35f0bb27db5e140940d00c673a67b0b9601bb348794a9
    image: docker.io/fortio/fortio:latest_release
    imageID: docker.io/fortio/fortio@sha256:196cdac4775f62d430c415a9de1a42c42094d8aec7964da3fb8348df9ded9623
    lastState: {}
    name: captured
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-10-25T00:13:29Z"
  - containerID: containerd://77803b4a0d078a779bc5a5e8be075b39d7ae9863a682f2990c88904bdaf024c0
    image: mcr.microsoft.com/oss/istio/proxyv2:1.17.8-distroless
    imageID: mcr.microsoft.com/oss/istio/proxyv2@sha256:13b4158b46ffe17608969db5317fe3bd3dc23abf188427adcfed716a158a0da1
    lastState: {}
    name: istio-proxy
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-10-25T00:13:30Z"
  - containerID: containerd://147c41699d0bc605c197f8a8ab29208d4b76f4f6a390e51bde413f5f9dd7b05f
    image: docker.io/cfmanteiga/alpine-bash-curl-jq:latest
    imageID: docker.io/cfmanteiga/alpine-bash-curl-jq@sha256:e09a3d5d52abb27830b44a2c279d09be66fad5bf476b3d02fb4a4a6125e377fc
    lastState: {}
    name: shell
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-10-25T00:13:30Z"
  - containerID: containerd://9869748911b45e48a762ab497f2228e72a3d475f1e3cc6e4b4822d87aa4e0495
    image: docker.io/fortio/fortio:latest_release
    imageID: docker.io/fortio/fortio@sha256:196cdac4775f62d430c415a9de1a42c42094d8aec7964da3fb8348df9ded9623
    lastState: {}
    name: uncaptured
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-10-25T00:13:30Z"
  hostIP: 10.224.108.66
  initContainerStatuses:
  - containerID: containerd://e976ad79a3d7bac5dddaf7c88888c76e68e654c71113c23c22eb1170ed9179de
    image: mcr.microsoft.com/oss/istio/proxyv2:1.17.8-distroless
    imageID: mcr.microsoft.com/oss/istio/proxyv2@sha256:13b4158b46ffe17608969db5317fe3bd3dc23abf188427adcfed716a158a0da1
    lastState: {}
    name: istio-init
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: containerd://e976ad79a3d7bac5dddaf7c88888c76e68e654c71113c23c22eb1170ed9179de
        exitCode: 0
        finishedAt: "2023-10-25T00:13:27Z"
        reason: Completed
        startedAt: "2023-10-25T00:13:27Z"
  phase: Running
  podIP: 10.224.108.75
  podIPs:
  - ip: 10.224.108.75
  qosClass: Burstable
  startTime: "2023-10-25T00:13:26Z"
