apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/default-container: captured
    kubectl.kubernetes.io/default-logs-container: captured
    linkerd.io/inject: disabled
    prometheus.io/path: /stats/prometheus
    prometheus.io/port: "15020"
    prometheus.io/scrape: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/interceptionMode: REDIRECT
    sidecar.istio.io/proxyCPU: 1000m
    sidecar.istio.io/proxyMemory: 512Mi
    sidecar.istio.io/status: '{"initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["workload-socket","credential-socket","workload-certs","istio-envoy","istio-data","istio-podinfo","istio-token","istiod-ca-cert"],"imagePullSecrets":null,"revision":"default"}'
    traffic.sidecar.istio.io/excludeInboundPorts: 8076,8077,8078,8081,9999
    traffic.sidecar.istio.io/excludeOutboundPorts: 80,8076,8077,8078, 8081
    traffic.sidecar.istio.io/includeOutboundIPRanges: 10.0.0.0/16
  creationTimestamp: "2023-03-29T23:17:35Z"
  generateName: fortioclient-667998d9bb-
  labels:
    app: fortioclient
    pod-template-hash: 667998d9bb
    security.istio.io/tlsMode: istio
    service.istio.io/canonical-name: fortioclient
    service.istio.io/canonical-revision: latest
  name: fortioclient-667998d9bb-6l7bx
  namespace: twopods-istio
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: fortioclient-667998d9bb
    uid: 14e2e31f-cc67-452b-936b-6807aaf4fced
  resourceVersion: "3028633"
  uid: 35c9a388-2fa5-4ccf-a366-9bfad649df29
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - fortioserver
        topologyKey: kubernetes.io/hostname
  containers:
  - args:
    - report
    image: fortio/fortio:latest_release
    imagePullPolicy: IfNotPresent
    name: captured
    resources:
      requests:
        cpu: 1500m
        memory: 1000Mi
    securityContext:
      runAsUser: 1
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/fortio
      name: shared-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-tzfhw
      readOnly: true
  - args:
    - /bin/sleep
    - 3650d
    image: cfmanteiga/alpine-bash-curl-jq:latest
    imagePullPolicy: Always
    name: shell
    resources: {}
    securityContext:
      runAsUser: 1
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/fortio
      name: shared-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-tzfhw
      readOnly: true
  - args:
    - report
    - -http-port
    - "8077"
    - -grpc-port
    - "8076"
    - -redirect-port
    - "8081"
    - -tcp-port
    - "8078"
    image: fortio/fortio:latest_release
    imagePullPolicy: IfNotPresent
    name: uncaptured
    resources:
      requests:
        cpu: 1500m
        memory: 1000Mi
    securityContext:
      runAsUser: 1
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-tzfhw
      readOnly: true
  - args:
    - proxy
    - sidecar
    - --domain
    - $(POD_NAMESPACE).svc.cluster.local
    - --proxyLogLevel=warning
    - --proxyComponentLogLevel=misc:error
    - --log_output_level=default:info
    - --concurrency
    - "2"
    env:
    - name: JWT_POLICY
      value: third-party-jwt
    - name: PILOT_CERT_PROVIDER
      value: istiod
    - name: CA_ADDR
      value: istiod.istio-system.svc:15012
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: INSTANCE_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.serviceAccountName
    - name: HOST_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: PROXY_CONFIG
      value: |
        {}
    - name: ISTIO_META_POD_PORTS
      value: |-
        [
        ]
    - name: ISTIO_META_APP_CONTAINERS
      value: captured,shell,uncaptured
    - name: ISTIO_META_CLUSTER_ID
      value: Kubernetes
    - name: ISTIO_META_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: ISTIO_META_INTERCEPTION_MODE
      value: REDIRECT
    - name: ISTIO_META_WORKLOAD_NAME
      value: fortioclient
    - name: ISTIO_META_OWNER
      value: kubernetes://apis/apps/v1/namespaces/twopods-istio/deployments/fortioclient
    - name: ISTIO_META_MESH_ID
      value: cluster.local
    - name: TRUST_DOMAIN
      value: cluster.local
    image: docker.io/istio/proxyv2:1.17.1
    imagePullPolicy: IfNotPresent
    name: istio-proxy
    ports:
    - containerPort: 15090
      name: http-envoy-prom
      protocol: TCP
    readinessProbe:
      failureThreshold: 30
      httpGet:
        path: /healthz/ready
        port: 15021
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 2
      successThreshold: 1
      timeoutSeconds: 3
    resources:
      requests:
        cpu: "1"
        memory: 512Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 1337
      runAsNonRoot: true
      runAsUser: 1337
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/workload-spiffe-uds
      name: workload-socket
    - mountPath: /var/run/secrets/credential-uds
      name: credential-socket
    - mountPath: /var/run/secrets/workload-spiffe-credentials
      name: workload-certs
    - mountPath: /var/run/secrets/istio
      name: istiod-ca-cert
    - mountPath: /var/lib/istio/data
      name: istio-data
    - mountPath: /etc/istio/proxy
      name: istio-envoy
    - mountPath: /var/run/secrets/tokens
      name: istio-token
    - mountPath: /etc/istio/pod
      name: istio-podinfo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-tzfhw
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - args:
    - istio-iptables
    - -p
    - "15001"
    - -z
    - "15006"
    - -u
    - "1337"
    - -m
    - REDIRECT
    - -i
    - 10.0.0.0/16
    - -x
    - ""
    - -b
    - '*'
    - -d
    - 15090,15021,8076,8077,8078,8081,9999,15020
    - -o
    - 80,8076,8077,8078, 8081
    - --log_output_level=default:info
    image: docker.io/istio/proxyv2:1.17.1
    imagePullPolicy: IfNotPresent
    name: istio-init
    resources:
      requests:
        cpu: "1"
        memory: 512Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: false
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-tzfhw
      readOnly: true
  nodeName: aks-agentpool-18453160-vmss000000
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - emptyDir: {}
    name: workload-socket
  - emptyDir: {}
    name: credential-socket
  - emptyDir: {}
    name: workload-certs
  - emptyDir:
      medium: Memory
    name: istio-envoy
  - emptyDir: {}
    name: istio-data
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels
        path: labels
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations
        path: annotations
    name: istio-podinfo
  - name: istio-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: istio-ca
          expirationSeconds: 43200
          path: istio-token
  - configMap:
      defaultMode: 420
      name: istio-ca-root-cert
    name: istiod-ca-cert
  - emptyDir: {}
    name: shared-data
  - name: kube-api-access-tzfhw
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-03-29T23:17:37Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-03-30T07:18:31Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-03-30T07:18:31Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-03-29T23:17:35Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://6cd639eae80b2089829101f5e9dbeac456d88516ee89dcd6b8426d98e37b71a1
    image: docker.io/fortio/fortio:latest_release
    imageID: docker.io/fortio/fortio@sha256:78172f349bf64c9debba3dfb3ed8b8e9fabbcd6a75f0c5d0e79378ffe493d4cb
    lastState: {}
    name: captured
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-03-29T23:17:37Z"
  - containerID: containerd://222c7b06bb4cb0c2afdeb32fa498f2fabbcefd5c5db04ea99ef99e95c71bfc3f
    image: docker.io/istio/proxyv2:1.17.1
    imageID: docker.io/istio/proxyv2@sha256:2152aea5fbe2de20f08f3e0412ad7a4cd54a492240ff40974261ee4bdb43871d
    lastState:
      terminated:
        containerID: containerd://c6137b176dc6ed8f7343758a90aed9239b00c8e8ffbb70c01cb1288e74173918
        exitCode: 0
        finishedAt: "2023-03-30T07:18:29Z"
        reason: Completed
        startedAt: "2023-03-30T05:41:33Z"
    name: istio-proxy
    ready: true
    restartCount: 4
    started: true
    state:
      running:
        startedAt: "2023-03-30T07:18:30Z"
  - containerID: containerd://15c839633e43ccf4345d3df238406991873ffa901ccec3240ff0f5491c897cc7
    image: docker.io/cfmanteiga/alpine-bash-curl-jq:latest
    imageID: docker.io/cfmanteiga/alpine-bash-curl-jq@sha256:e09a3d5d52abb27830b44a2c279d09be66fad5bf476b3d02fb4a4a6125e377fc
    lastState: {}
    name: shell
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-03-29T23:17:37Z"
  - containerID: containerd://1229afa298f0304fb2647ea1a53a9b4cf0b96f56f731f1cde89387bb95702f0e
    image: docker.io/fortio/fortio:latest_release
    imageID: docker.io/fortio/fortio@sha256:78172f349bf64c9debba3dfb3ed8b8e9fabbcd6a75f0c5d0e79378ffe493d4cb
    lastState: {}
    name: uncaptured
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-03-29T23:17:37Z"
  hostIP: 10.224.180.2
  initContainerStatuses:
  - containerID: containerd://a99092b935023169cb0638ccf2b898b3e6aabb94b72b46f281e2785a8e3300d5
    image: docker.io/istio/proxyv2:1.17.1
    imageID: docker.io/istio/proxyv2@sha256:2152aea5fbe2de20f08f3e0412ad7a4cd54a492240ff40974261ee4bdb43871d
    lastState: {}
    name: istio-init
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: containerd://a99092b935023169cb0638ccf2b898b3e6aabb94b72b46f281e2785a8e3300d5
        exitCode: 0
        finishedAt: "2023-03-29T23:17:36Z"
        reason: Completed
        startedAt: "2023-03-29T23:17:36Z"
  phase: Running
  podIP: 10.244.1.15
  podIPs:
  - ip: 10.244.1.15
  qosClass: Burstable
  startTime: "2023-03-29T23:17:35Z"
